#pragma once

#include "API/Phoenix_Types.h"
#include "API/Phoenix_Keys.h"
#include "API/Phoenix_Debug.h"
#include "API/Phoenix_Time.h"
#include "API/Phoenix_Input.h"
#include "API/Phoenix_Scene.h"
#include "API/Phoenix_GameObject.h"
#include "IScript.h"
#include "ScriptExport.h"

using Phoenix::Vec2;
using Phoenix::Vec3;
using Phoenix::Vec4;
using Phoenix::Quat;
using Phoenix::Mat4;
using Phoenix::Color;
using Phoenix::Key;
using Phoenix::MouseButton;
using Phoenix::GamepadButton;
using Phoenix::GamepadAxis;
using Phoenix::Input;
using Phoenix::Time;
using Phoenix::Debug;
using Phoenix::Scene;
using Phoenix::GetTransform;
using Phoenix::GetRigidbody;
using Phoenix::GetAnimation;
using Phoenix::GetParticles;
using Phoenix::SetActive;
using Phoenix::IsActive;
using Phoenix::GetName;
using Phoenix::Position;
using Phoenix::Scale;
using Phoenix::Rotation;
